---
on:
  workflow_dispatch:
  workflow_call:
  push:
    paths-ignore:
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'

jobs:
  shellcheck:
    uses: ./.github/workflows/workflows/shellcheck.yml

  svglint:
    uses: ./.github/workflows/workflows/svglint.yml

  image-generation:
    needs:
        - shellcheck
        - svglint
    uses: ./.github/workflows/workflows/svglint.yml
